package mb.demo.applications.ai.agents.models;

import java.util.Map;

public record EndpointTask(
        String url,
        String method,
        String operationId,
        String payload,             // The JSON generated by the AI
        Map<String, String> headers // Required headers (e.g., Content-Type)
) {
}
