openapi: 3.0.1
info:
  title: ai agents api
  description: 'An api to demonstrate working with ai agents'
  version: '1.1.1'
servers:
  - url: 'https://localhost:8080'
    description: 'local'
paths:
  /api/test/public/openapi:
    post:
      summary: Upload an OpenAPI spec to start testing
      operationId: testPublicSpec
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The OpenAPI YAML or JSON file to be tested.
      responses:
        '200':
          description: Testing started successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestResult'
components:
  schemas:
    TestResult:
      type: object
      properties:
        url:
          type: string
        method:
          type: string
        operationId:
          type: string
        payload:
          type: string
        statusCode:
          type: integer
        responseBody:
          type: string